var data = [
    {
      "latitude": "4.692501",
      "longitude": "-74.139995",
      "fuel": 100,
      "operation": "-",
      "position": "E4",
      "temperature": 20,
      "ignition": "off",
      "driver": "-",
      "battery": "12,5",
      "msg": "-",
      "panic": 0,
      "speed": 0
    },
    {
      "latitude": "4.692501",
      "longitude": "-74.139995",
      "fuel": 100,
      "operation": "AER058",
      "position": "E8",
      "temperature": 22,
      "ignition": "on",
      "driver": "James Smith",
      "battery": "12,5",
      "msg": "Next operation E13",
      "panic": 0,
      "speed": 10
    },
    {
      "latitude": "4.692581",
      "longitude": "-74.139921",
      "fuel": 100,
      "operation": "AER058",
      "position": "E8",
      "temperature": 24,
      "ignition": "on",
      "driver": "James Smith",
      "battery": "13,2",
      "msg": "Next operation E13",
      "panic": 0,
      "speed": 10
    },
    {
      "latitude": "4.692514",
      "longitude": "-74.139834",
      "fuel": 98,
      "operation": "AER058",
      "position": "E8",
      "temperature": 24,
      "ignition": "on",
      "driver": "James Smith",
      "battery": "13,2",
      "msg": "Next operation E13",
      "panic": 0,
      "speed": 11
    },
    {
      "latitude": "4.692410",
      "longitude": "-74.139697",
      "fuel": 97,
      "operation": "AER058",
      "position": "E8",
      "temperature": 24,
      "ignition": "on",
      "driver": "James Smith",
      "battery": "13,5",
      "msg": "Next operation E13",
      "panic": 0,
      "speed": 12
    },
    {
      "latitude": "4.692267",
      "longitude": "-74.139516",
      "fuel": 96,
      "operation": "AER058",
      "position": "E8",
      "temperature": 24,
      "ignition": "on",
      "driver": "James Smith",
      "battery": 13.5,
      "msg": "Next operation E13",
      "panic": 0,
      "speed": 12
    },
    {
      "latitude": "4.692139",
      "longitude": "-74.139343",
      "fuel": 95,
      "operation": "AER058",
      "position": "E8",
      "temperature": 24,
      "ignition": "on",
      "driver": "James Smith",
      "battery": 13.5,
      "msg": "Next operation E13",
      "panic": 0,
      "speed": 13
    },
    {
      "latitude": "4.692188",
      "longitude": "-74.139220",
      "fuel": 94,
      "operation": "AER058",
      "position": "E8",
      "temperature": 24,
      "ignition": "on",
      "driver": "James Smith",
      "battery": 13.5,
      "msg": "Next operation E13",
      "panic": 0,
      "speed": 14
    },
    {
      "latitude": "4.692313",
      "longitude": "-74.139121",
      "fuel": 94,
      "operation": "AER058",
      "position": "E8",
      "temperature": 24,
      "ignition": "on",
      "driver": "James Smith",
      "battery": 13.5,
      "msg": "Next operation E13",
      "panic": 0,
      "speed": 14
    },
    {
      "latitude": "4.692543",
      "longitude": "-74.138885",
      "fuel": 93,
      "operation": "AER058",
      "position": "E8",
      "temperature": 24,
      "ignition": "on",
      "driver": "James Smith",
      "battery": 13.5,
      "msg": "Next operation E13",
      "panic": 0,
      "speed": 14
    },
    {
      "latitude": "4.692466",
      "longitude": "-74.138733",
      "fuel": 90,
      "operation": "AER058",
      "position": "E8",
      "temperature": 24,
      "ignition": "on",
      "driver": "James Smith",
      "battery": 13.5,
      "msg": "Next operation E13",
      "panic": 0,
      "speed": 12
    },
    {
      "latitude": "4.692275",
      "longitude": "-74.138487",
      "fuel": 78,
      "operation": "AER058",
      "position": "E9",
      "temperature": 35,
      "ignition": "on",
      "driver": "James Smith",
      "battery": 13.5,
      "msg": "Next operation E13",
      "panic": 0,
      "speed": 14
    },
    {
      "latitude": "4.692163",
      "longitude": "-74.138337",
      "fuel": 77,
      "operation": "AER058",
      "position": "E10",
      "temperature": 34,
      "ignition": "on",
      "driver": "James Smith",
      "battery": 13.5,
      "msg": "Next operation E13",
      "panic": 0,
      "speed": 14
    },
    {
      "latitude": "4.692019",
      "longitude": "-74.138141",
      "fuel": 76,
      "operation": "AER058",
      "position": "E10",
      "temperature": 40,
      "ignition": "on",
      "driver": "James Smith",
      "battery": 13.5,
      "msg": "Next operation E13",
      "panic": 0,
      "speed": 12
    },
    {
      "latitude": "4.691837",
      "longitude": "-74.137900",
      "fuel": 75,
      "operation": "AER058",
      "position": "E11",
      "temperature": 40,
      "ignition": "on",
      "driver": "James Smith",
      "battery": 13.5,
      "msg": "Next operation E13",
      "panic": 0,
      "speed": 12
    },
    {
      "latitude": "4.690840",
      "longitude": "-74.136586",
      "fuel": 74,
      "operation": "AER058",
      "position": "E12",
      "temperature": 50,
      "ignition": "on",
      "driver": "James Smith",
      "battery": 13.5,
      "msg": "Next operation E13",
      "panic": 0,
      "speed": 13
    },
    {
      "latitude": "4.690492",
      "longitude": "-74.136138",
      "fuel": 72,
      "operation": "AER058",
      "position": "E13",
      "temperature": 60,
      "ignition": "on",
      "driver": "James Smith",
      "battery": 13.5,
      "msg": "Next operation E13",
      "panic": 0,
      "speed": 13
    },
    {
      "latitude": "4.690392",
      "longitude": "-74.136194",
      "fuel": 60,
      "operation": "AER058",
      "position": "E13",
      "temperature": 60,
      "ignition": "on",
      "driver": "James Smith",
      "battery": 13.5,
      "msg": "Attention",
      "panic": 1,
      "speed": 7
    },
    {
      "latitude": "4.690319",
      "longitude": "-74.136243",
      "fuel": 50,
      "operation": "AER058",
      "position": "E13",
      "temperature": 60,
      "ignition": "on",
      "driver": "James Smith",
      "battery": 13.5,
      "msg": "Attention",
      "panic": 1,
      "speed": 5
    },
    {
      "latitude": "4.690296",
      "longitude": "-74.136368",
      "fuel": 40,
      "operation": "AER058",
      "position": "E13",
      "temperature": 60,
      "ignition": "on",
      "driver": "James Smith",
      "battery": 13.5,
      "msg": "Attention",
      "panic": 1,
      "speed": 5
    },
    {
      "latitude": "4.690285",
      "longitude": "-74.136481",
      "fuel": 38,
      "operation": "AER058",
      "position": "E13",
      "temperature": 60,
      "ignition": "on",
      "driver": "James Smith",
      "battery": 13.5,
      "msg": "Attention",
      "panic": 1,
      "speed": 8
    },
    {
      "latitude": "4.690390",
      "longitude": "-74.136210",
      "fuel": 37,
      "operation": "AER058",
      "position": "E13",
      "temperature": 60,
      "ignition": "on",
      "driver": "James Smith",
      "battery": 13.5,
      "msg": "Attention",
      "panic": 1,
      "speed": 8
    },
    {
      "latitude": "4.690492",
      "longitude": "-74.136138",
      "fuel": 35,
      "operation": "AER058",
      "position": "E13",
      "temperature": 60,
      "ignition": "on",
      "driver": "James Smith",
      "battery": 13.5,
      "msg": "Next operation E13",
      "panic": 0,
      "speed": 10
    },
    {
      "latitude": "4.690840",
      "longitude": "-74.136586",
      "fuel": 34,
      "operation": "AER058",
      "position": "E12",
      "temperature": 70,
      "ignition": "on",
      "driver": "James Smith",
      "battery": 13.5,
      "msg": "Next operation E13",
      "panic": 0,
      "speed": 10
    },
    {
      "latitude": "4.691837",
      "longitude": "-74.137900",
      "fuel": 33,
      "operation": "AER058",
      "position": "E11",
      "temperature": 80,
      "ignition": "on",
      "driver": "James Smith",
      "battery": 13.5,
      "msg": "Next operation E13",
      "panic": 0,
      "speed": 11
    },
    {
      "latitude": "4.692019",
      "longitude": "-74.138141",
      "fuel": 32,
      "operation": "AER058",
      "position": "E10",
      "temperature": 80,
      "ignition": "on",
      "driver": "James Smith",
      "battery": 13.5,
      "msg": "Next operation E13",
      "panic": 0,
      "speed": 11
    },
    {
      "latitude": "4.692163",
      "longitude": "-74.138337",
      "fuel": 31,
      "operation": "AER058",
      "position": "E10",
      "temperature": 80,
      "ignition": "on",
      "driver": "James Smith",
      "battery": 13.5,
      "msg": "Next operation E13",
      "panic": 0,
      "speed": 11
    },
    {
      "latitude": "4.692275",
      "longitude": "-74.138487",
      "fuel": 30,
      "operation": "AER058",
      "position": "E9",
      "temperature": 80,
      "ignition": "on",
      "driver": "James Smith",
      "battery": 13.5,
      "msg": "Next operation E13",
      "panic": 0,
      "speed": 11
    },
    {
      "latitude": "4.692466",
      "longitude": "-74.138733",
      "fuel": 29,
      "operation": "AER058",
      "position": "E8",
      "temperature": 85,
      "ignition": "on",
      "driver": "James Smith",
      "battery": 13.5,
      "msg": "Next operation E13",
      "panic": 0,
      "speed": 12
    },
    {
      "latitude": "4.692543",
      "longitude": "-74.138885",
      "fuel": 28,
      "operation": "AER058",
      "position": "E8",
      "temperature": 85,
      "ignition": "on",
      "driver": "James Smith",
      "battery": 13.5,
      "msg": "Next operation E13",
      "panic": 0,
      "speed": 12
    },
    {
      "latitude": "4.692313",
      "longitude": "-74.139121",
      "fuel": 27,
      "operation": "AER058",
      "position": "E8",
      "temperature": 90,
      "ignition": "on",
      "driver": "James Smith",
      "battery": 13.5,
      "msg": "Next operation E13",
      "panic": 0,
      "speed": 12
    },
    {
      "latitude": "4.692188",
      "longitude": "-74.139220",
      "fuel": 26,
      "operation": "AER058",
      "position": "E8",
      "temperature": 92,
      "ignition": "on",
      "driver": "James Smith",
      "battery": 13.5,
      "msg": "Next operation E13",
      "panic": 0,
      "speed": 12
    },
    {
      "latitude": "4.692139",
      "longitude": "-74.139343",
      "fuel": 25,
      "operation": "AER058",
      "position": "E8",
      "temperature": 92,
      "ignition": "on",
      "driver": "James Smith",
      "battery": 13.5,
      "msg": "Next operation E13",
      "panic": 0,
      "speed": 13
    },
    {
      "latitude": "4.692267",
      "longitude": "-74.139516",
      "fuel": 24,
      "operation": "AER058",
      "position": "E8",
      "temperature": 92,
      "ignition": "on",
      "driver": "James Smith",
      "battery": 13.5,
      "msg": "Next operation E13",
      "panic": 0,
      "speed": 13
    },
    {
      "latitude": "4.692410",
      "longitude": "-74.139697",
      "fuel": 23,
      "operation": "AER058",
      "position": "E8",
      "temperature": 92,
      "ignition": "on",
      "driver": "James Smith",
      "battery": "13,5",
      "msg": "Next operation E13",
      "panic": 1,
      "speed": 14
    },
    {
      "latitude": "4.692514",
      "longitude": "-74.139834",
      "fuel": 22,
      "operation": "AER058",
      "position": "E8",
      "temperature": 92,
      "ignition": "on",
      "driver": "James Smith",
      "battery": "13,2",
      "msg": "Next operation E13",
      "panic": 1,
      "speed": 12
    },
    {
      "latitude": "4.692581",
      "longitude": "-74.139921",
      "fuel": 22,
      "operation": "AER058",
      "position": "E8",
      "temperature": 92,
      "ignition": "on",
      "driver": "James Smith",
      "battery": "13,2",
      "msg": "Next operation E13",
      "panic": 1,
      "speed": 12
    },
    {
      "latitude": "4.692501",
      "longitude": "-74.139995",
      "fuel": 22,
      "operation": "AER058",
      "position": "E8",
      "temperature": 92,
      "ignition": "on",
      "driver": "James Smith",
      "battery": "12,5",
      "msg": "Next operation E13",
      "panic": 1,
      "speed": 10
    },
    {
      "latitude": "4.692501",
      "longitude": "-74.139995",
      "fuel": 23,
      "operation": "AER058",
      "position": "E4",
      "temperature": 90,
      "ignition": "off",
      "driver": "-",
      "battery": "12,5",
      "msg": "refueling",
      "panic": 1,
      "speed": 0
    },
    {
      "latitude": "4.692501",
      "longitude": "-74.139995",
      "fuel": 24,
      "operation": "AER058",
      "position": "E4",
      "temperature": 70,
      "ignition": "off",
      "driver": "-",
      "battery": "12,5",
      "msg": "refueling",
      "panic": 1,
      "speed": 0
    },
    {
      "latitude": "4.692501",
      "longitude": "-74.139995",
      "fuel": 30,
      "operation": "AER058",
      "position": "E4",
      "temperature": 60,
      "ignition": "off",
      "driver": "-",
      "battery": "12,5",
      "msg": "refueling",
      "panic": 0,
      "speed": 0
    },
    {
      "latitude": "4.692501",
      "longitude": "-74.139995",
      "fuel": 40,
      "operation": "AER058",
      "position": "E4",
      "temperature": 50,
      "ignition": "off",
      "driver": "-",
      "battery": "12,5",
      "msg": "refueling",
      "panic": 0,
      "speed": 0
    },
    {
      "latitude": "4.692501",
      "longitude": "-74.139995",
      "fuel": 50,
      "operation": "AER058",
      "position": "E4",
      "temperature": 40,
      "ignition": "off",
      "driver": "-",
      "battery": "12,5",
      "msg": "refueling",
      "panic": 0,
      "speed": 0
    },
    {
      "latitude": "4.692501",
      "longitude": "-74.139995",
      "fuel": 70,
      "operation": "AER058",
      "position": "E4",
      "temperature": 30,
      "ignition": "off",
      "driver": "-",
      "battery": "12,5",
      "msg": "refueling",
      "panic": 0,
      "speed": 0
    },
    {
      "latitude": "4.692501",
      "longitude": "-74.139995",
      "fuel": 100,
      "operation": "AER058",
      "position": "E4",
      "temperature": 20,
      "ignition": "off",
      "driver": "-",
      "battery": "12,5",
      "msg": "refueling",
      "panic": 0,
      "speed": 0
    }
  ]
  
  var i = parseInt(metadata.ss_index);
  
  return {msg: data[i], metadata: {index:i,dataLength:data.length}, msgType: msgType};